config/routes.rb
Rails.application.routes.draw do
  root to: 'currencies#index'
  post '/update', to: 'currencies#update'
  post '/calculate', to: 'currencies#calculate'

  resources :currencies, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ApplicationRecord
  def self.call(url)
    headers = {
      'X-CMC_PRO_API_KEY' => ENV['COINMARKETCAP_KEY']
    }
    response = HTTParty.get(url,:headers => headers).parsed_response
  end

  def self.get_all_data(quantity)
    call = self.call("https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?limit=#{quantity}&convert=EUR")
    data = call["data"]
    return data
  end

  def self.check_if_exists_in_db(hash)
    exists = false
    Currency.all.each do |db_crypto|
      if db_crypto.id_CMC == hash["id"]
        exists = true
      end
    end
    return exists
  end
  

  def self.update_data(quantity)
    data = Currency.get_all_data(quantity)
    data.sort_by! { |k| k["rank"] }
    data.each do |crypto|
      exist = Currency.check_if_exists_in_db(crypto)
      if exist == true
        Currency.where(id_CMC: crypto["id"]).update(
          price: crypto["quote"]["EUR"]["price"].round(4),
          slug: crypto["slug"],
          rank: crypto["cmc_rank"],
          currency_symbol: crypto["symbol"].downcase
        )
      else
        Currency.create!([
          {
            name: crypto["name"],
            currency_symbol: crypto["symbol"].downcase,
            slug: crypto["slug"],
            price: crypto["quote"]["EUR"]["price"].round(4),
            market_cap: crypto["quote"]["EUR"]["market_cap"],
            max_supply: crypto["max_supply"],
            rank: crypto["cmc_rank"],
            logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/#{crypto["id"]}.png",
            id_CMC: crypto["id"],
            portfolio_value: 0,
            portfolio_qty: 0
          }
        ])
      end
    end
  end

  def check_value(amount)
    result = (price.to_f * amount.to_f).round(4)
    return result.round(2)
  end

  def self.portfolio_total_value
    currencies = Currency.all
    total = 0
    currencies.each do |x|
      total = total + x.portfolio_value
    end
    return total.round(2)
  end

  def calculate_porcentage(total, amount)
    porcentage = amount/total*100
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  def index
    @currencies = Currency.all.order('rank ASC')
    @total = Currency.portfolio_total_value
  end

  def show
    @id = params[:id]
    @currency = Currency.find(@id)
    @total = Currency.portfolio_total_value
    @porcentage = @currency.calculate_porcentage(@total, @currency.portfolio_value).round(2)
  end

  def update
    quantity = 200
    @data = Currency.get_all_data(quantity)
    Currency.update_data(quantity)
    redirect_to currencies_path
  end

  def calculate
    id = params[:id]
    amount = params[:amount].to_f
    currency = Currency.find_by(id_CMC: id)
    @value = currency.check_value(amount)
    currency.update(:portfolio_value => @value, :portfolio_qty => amount)
    redirect_to currencies_path
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/index.html.erb
<div class="m-5">
  <h1>Crypto Porftolio</h1>
  <h2>Total Portolio value: <%= @total %> EUR</h2>
</div>
<%= button_to 'Price Update', update_path, method: :post, class: "btn btn-success ml-5" %>
<hr>
<div class="m-5">
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th scope="col">Rank</th>
        <th scope="col">Crypto</th>
        <th scope="col" class="text-center">Symbol</th>
        <th scope="col">Slug</th>
        <th scope="col" class="text-right pr-4">Price (€)</th>
        <th scope="col">CMC #id</th>
        <th scope="col">My portfolio</th>
        <th scope="col"></th>
        <th scope="col">Qty</th>
        <th scope="col">TOTAL EUR</th>
      </tr>
    </thead>

    <tbody>
      <% @currencies.order('rank ASC').each do |crypto| %>
        <tr>
          <td><img style="width:35px;" src=<%= crypto.logo %>></td>
          <td><%= crypto.rank %></td>
          <td><a href="<%= currency_path(crypto.id) %>"><%= crypto.name %></a></td>
          <td class="text-center"><%= crypto.currency_symbol %></td>      
          <td><%= crypto.slug %></td>
          <td class="text-right"><%= crypto.price.round(4) %></td>
          <td><%= crypto.id_CMC %></td>
          <%= form_tag calculate_path do %>
            <td>
              <%= number_field_tag 'amount', nil, min: 0, step: 0.01 %>
              <%= hidden_field_tag :id, crypto.id_CMC %>
            </td>
            <td>
              <%= submit_tag "+", :class=>"btn btn-primary" %>
            </td>
          <% end %>
          <td><%= crypto.portfolio_qty %></td>
          <td><%= crypto.portfolio_value %></td>
        </tr>
      <% end%>
    </tbody>
  </table>
</div>

app/views/currencies/show.html.erb
<div class="m-5">
<h1><%= @currency.name %></h1>
<h2>Total Portfolio value: <%= @total %> EUR</h2>
<img class="img-thumbnail" src="<%= @currency.logo %>">
<table class="table my-5">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Symbol</th>
      <th scope="col">Max Supply</th>
      <th scope="col">Slug</th>
      <th scope="col">Price (€)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @id %></td>
      <td><%= @currency.name %></td>
      <td><%= @currency.currency_symbol %></td>
      <td><%= @currency.max_supply %></td>
      <td><%= @currency.slug %></td>
      <td><%= @currency.price.round(4) %></td>
    </tr>
  </tbody>
</table>

<h2>My Portfolio</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Qty</th>
        <th scope="col">EUR Value</th>
        <th scope="col">%</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @currency.portfolio_qty %></td>
          <td><%= @currency.portfolio_value %></td>
            <td><%= @porcentage %></td>
          </tr>
    </tbody>
  </table>
<hr>
<a class="btn btn-warning" href="<%= currencies_path %>">Home</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoPortfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>